#!/usr/bin/env bash

set -euo pipefail

# get my stuff
[ ! -e ~/.git ] &&
    cd /tmp &&
         rm -rf dotfiles &&
         git clone https://github.com/massemanet/dotfiles.debian dotfiles &&
         cd dotfiles &&
         git remote set-url origin git@github.com:massemanet/dotfiles.debian &&
         mv .git ~ &&
         cd ~ &&
         git reset --hard

# get the pet files
[ -d ~/pet ] ||
    ~/bin/pet download

## install all the things
brew update &&
    brew tap homebrew/cask &&
    brew install \
         bash bash-completion coreutils curl findutils \
         gawk git gnu-sed gpg grep gzip \
         jq make mosh pass pstree shellcheck tree &&
    brew install --cask \
         emacs keybase lastfm slack spotify tunnelblick &&
    brew install \
         erlang rebar3 rust

# chromium is special
bin/install.sh chromium

# uncrapify the shell
sudo tee /etc/shells <<HERE
/usr/local/opt/bash/bin/bash
/bin/bash
/bin/sh
/bin/zsh
HERE
sudo chsh -s /usr/local/opt/bash/bin/bash
